version: '3.3'

services:
  django:
    build: ./rutube_site/
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: sh -c "python manage.py runserver 0.0.0.0:8000 & python tg_bot/bot.py"

  react:
    build:
      context: ./rutube_site/front-end
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./rutube_site/front-end:/app
    ports:
      - "3000:3000"
      - "5173:5173"  # Добавляем порт Vite
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0  # Открываем для внешнего доступа
    depends_on:
      - django
volumes:
  media:
  static: