# Generated by Django 5.0.4 on 2024-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Запрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('class_1', models.TextField(verbose_name='Класс 1')),
                ('class_2', models.TextField(verbose_name='Класс 2')),
            ],
            options={
                'verbose_name': 'Ответ на запрос',
                'verbose_name_plural': 'Ответы на запросы',
                'ordering': ['-id'],
            },
        ),
    ]
